const NOCODB_BASE_URL = 'https://nocodb.qurvii.com/api/v2';
const NOCODB_API_TOKEN = 'QXOzKHJ982NgA2AIc8jDqK0lC5CdWEcCwacCIsaJ';
const NOCODB_ORDERS_TABLE_NAME = 'm9lzzdoc2x4zxun';
const NOCODB_ORDERS_VIEW_ID = 'vwwsae9mswybppcm';

const NOCODB_SCANNING_TABLE_NAME = 'misuaa9cvim4h13';
const NOCODB_SCANNING_VIEW_ID = 'vwx3yogyd9jcoqbk';

const TAILOR_LOCATION_ID = 145;

export {
  NOCODB_BASE_URL,
  NOCODB_API_TOKEN,
  NOCODB_ORDERS_TABLE_NAME,
  NOCODB_ORDERS_VIEW_ID,
  NOCODB_SCANNING_TABLE_NAME,
  NOCODB_SCANNING_VIEW_ID,
  TAILOR_LOCATION_ID,
};
